module.exports = function (action) {
    switch (action) {
        case 0:
            return "ActionAuth";
        case 1:
            return "ActionAutoMatch"
        case 2:
            return "ActionCreateRoom"
        case 3:
            return "ActionGetRooms"
        case 4:
            return "ActionJoinRoom"
        case 5:
            return "ActionPing"
        case 6:
            return "ActionInviteUser"
        case 7:
            return "ActionKickUser"
        case 8:
            return "ActionGetInviteList"
        case 9:
            return "ActionAcceptInvite"
        case 10:
            return "ActionFindUser"
        case 11:
            return "ActionNotification"
        case 12:
            return "ActionSubscribe"
        case 13:
            return "ActionChat"
        case 14:
            return "ActionUnSubscribe"
        case 15:
            return "ActionInviteNotif"
        case 100:
            return "Error"
        case "ActionAuth":
            return 0;
        case "ActionAutoMatch":
            return 1
        case "ActionCreateRoom":
            return 2
        case "ActionGetRooms":
            return 3
        case "ActionJoinRoom":
            return 4
        case "ActionPing":
            return 5
        case "ActionInviteUser":
            return 6
        case "ActionKickUser":
            return 7
        case "ActionGetInviteList":
            return 8
        case "ActionAcceptInvite":
            return 9
        case "ActionFindUser":
            return 10
        case "ActionNotification":
            return 11
        case "ActionSubscribe":
            return 12
        case "ActionChat":
            return 13
        case "ActionUnSubscribe":
            return 14
        case "ActionInviteNotif":
            return 15
        case "Error":
            return 100
    }
}